<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, minimum-scale=1.0">
  <!-- styles -->
  <link rel="stylesheet" href="css/vendor/font-awesome.min.css">
  <link rel="stylesheet" href="css/vendor/simple-line-icons.css">
  <link rel="stylesheet" href="css/vendor/magnific-popup.css">
  <link rel="stylesheet" href="css/style.min.css">
  <!-- favicon -->
  <link rel="icon" href="favicon.ico">
  <title>PC WORLDZ | Product Page</title>
</head>
<body>

  <!-- FORM POPUP -->
  <?php
echo '<div id="login-popup" class="form-popup medium mfp-hide">';
echo '<!-- CLOSE BTN -->';
echo '<svg class="svg-cross medium close-btn">';
echo '<use xlink:href="#svg-cross"></use>';
echo '</svg>';
echo '<!-- /CLOSE BTN -->';
echo '';
echo '<!-- FORM POPUP COLUMN -->';
echo '<div class="form-popup-column small">';
echo '<h2 class="subsection-title medium">Register now!</h2>';
echo '<hr class="line-separator">';
echo '<p class="small">Fill all the requirements on the space provided.</p>';
echo '<!-- FORM -->';
echo '<form>';
echo '<!-- FORM ROW -->';
echo '<div class="form-row">';
echo '<label for="email" class="rl-label">Email</label>';
echo '<input type="text" id="email" name="email" placeholder="Enter your email...">';
echo '</div>';
echo '<!-- /FORM ROW -->';
echo '';
echo '<!-- FORM ROW -->';
echo '<div class="form-row">';
echo '<label for="password" class="rl-label">Password</label>';
echo '<input type="password" id="password" name="password" placeholder="Enter your password...">';
echo '</div>';
echo '<!-- /FORM ROW -->';
echo '';
echo '<!-- FORM ROW -->';
echo '<div class="form-row separated">';
echo '<button class="button dark full">Register to PC WORLDZ!</button>';
echo '</div>';
echo '<!-- /FORM ROW -->';
echo '</form>';
echo '<!-- /FORM -->';
echo '</div>';
echo '<!-- /FORM POPUP COLUMN -->';
echo '';
echo '<!-- FORM POPUP COLUMN SEPARATOR -->';
echo '<div class="form-popup-column-separator"></div>';
echo '<!-- /FORM POPUP COLUMN SEPARATOR -->';
echo '';
echo '<!-- FORM POPUP COLUMN -->';
echo '<div class="form-popup-column small">';
echo '<h2 class="subsection-title medium">Login to PC WORLDZ</h2>';
echo '<hr class="line-separator">';
echo '<!-- FORM -->';
echo '<form>';
echo '<!-- FORM ROW -->';
echo '<div class="form-row">';
echo '<label for="username" class="rl-label">Username</label>';
echo '<input type="text" id="username" name="username" placeholder="Enter your username...">';
echo '</div>';
echo '<!-- /FORM ROW -->';
echo '';
echo '<!-- FORM ROW -->';
echo '<div class="form-row">';
echo '<label for="password2" class="rl-label">Password</label>';
echo '<input type="password" id="password2" name="password2" placeholder="Enter your password...">';
echo '</div>';
echo '<!-- /FORM ROW -->';
echo '';
echo '<!-- FORM ROW -->';
echo '<div class="form-row">';
echo '<!-- CHECKBOX -->';
echo '<input type="checkbox" id="keep_logged" name="keep_logged" checked>';
echo '<label class="checkbox" for="keep_logged">';
echo '<span class="box">';
echo '<!-- SVG CHECK -->';
echo '<svg class="svg-check">';
echo '<use xlink:href="#svg-check"></use>';
echo '</svg>';
echo '<!-- /SVG CHECK -->';
echo '</span>';
echo 'Keep me logged in';
echo '</label>';
echo '<!-- /CHECKBOX -->';
echo '';
echo '<a href="#" class="link">Forgot password?</a>';
echo '</div>';
echo '<!-- /FORM ROW -->';
echo '';
echo '<!-- FORM ROW -->';
echo '<div class="form-row short-space separated">';
echo '<button class="button full">Login to your Account</button>';
echo '</div>';
echo '<!-- /FORM ROW -->';
echo '';
echo '<!-- FORM ROW -->';
echo '<div class="form-row">';
echo '<div class="half">';
echo '<a href="#" class="button blue full">Facebook Login</a>';
echo '</div>';
echo '<div class="half">';
echo '<a href="#" class="button lightblue full">Twitter Login</a>';
echo '</div>';
echo '</div>';
echo '<!-- /FORM ROW -->';
echo '</form>';
echo '<!-- /FORM -->';
echo '</div>';
echo '<!-- /FORM POPUP COLUMN -->';
echo '</div>';
echo '<!-- /FORM POPUP -->';
echo '';
echo '<!-- FORM POPUP -->';
echo '<div id="review-popup" class="form-popup mfp-hide">';
echo '<!-- CLOSE BTN -->';
echo '<svg class="svg-cross medium close-btn">';
echo '<use xlink:href="#svg-cross"></use>';
echo '</svg>';
echo '<!-- /CLOSE BTN -->';
echo '';
echo '<!-- FORM POPUP COLUMN -->';
echo '<div class="form-popup-column centered">';
echo '<h2 class="subsection-title medium">Write a Review</h2>';
echo '<hr class="line-separator">';
echo '<p class="small">Write the reviews on the space provided.</p>';
echo '<!-- FORM -->';
echo '<form>';
echo '<!-- FORM ROW -->';
echo '<div class="form-row">';
echo '<label for="review_title" class="rl-label">Review Title</label>';
echo '<input type="text" id="review_title" name="review_title" placeholder="Enter your title...">';
echo '</div>';
echo '<!-- /FORM ROW -->';
echo '';
echo '<!-- FORM ROW -->';
echo '<div class="form-row">';
echo '<label for="comment" class="rl-label">Additional Comments</label>';
echo '<textarea id="comment" name="comment" placeholder="Write your review here..."></textarea>';
echo '</div>';
echo '<!-- /FORM ROW -->';
echo '';
echo '<!-- FORM ROW -->';
echo '<div class="form-row">';
echo '<label class="rl-label inline">Stars Rating:</label>';
echo '<!-- RATING -->';
echo '<ul class="rating medium changeable">';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '</ul>';
echo '<!-- /RATING -->';
echo '</div>';
echo '<!-- /FORM ROW -->';
echo '';
echo '<!-- FORM ROW -->';
echo '<div class="form-row">';
echo '<button class="button medium full with-icon">';
echo 'Post your Review';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</button>';
echo '</div>';
echo '<!-- /FORM ROW -->';
echo '</form>';
echo '<!-- /FORM -->';
echo '</div>';
echo '<!-- /FORM POPUP COLUMN -->';
echo '</div>';
echo '<!-- /FORM POPUP -->';
echo '';
echo '<!-- WIDGET LINE WRAP -->';
echo '<div class="widget-line-wrap widget-line-1">';
echo '<!-- WIDGET LINE -->';
echo '<div class="widget-line">';
echo '<!-- ACTIONS LIST -->';
echo '<ul class="actions-list left">';
echo '<!-- ACTIONS LIST ITEM -->';
echo '<li class="actions-list-item">';
echo '<!-- SOCIAL LINK -->';
echo '<div class="social-link">';
echo '<a href="#">';
echo '<i class="fa fa-facebook"></i>';
echo '</a>';
echo '</div>';
echo '<!-- /SOCIAL LINK -->';
echo '</li>';
echo '<!-- ACTIONS LIST ITEM -->';
echo '';
echo '<!-- ACTIONS LIST ITEM -->';
echo '<li class="actions-list-item">';
echo '<!-- SOCIAL LINK -->';
echo '<div class="social-link">';
echo '<a href="#">';
echo '<i class="fa fa-twitter"></i>';
echo '</a>';
echo '</div>';
echo '<!-- /SOCIAL LINK -->';
echo '</li>';
echo '<!-- ACTIONS LIST ITEM -->';
echo '';
echo '<!-- ACTIONS LIST ITEM -->';
echo '<li class="actions-list-item">';
echo '<!-- SOCIAL LINK -->';
echo '<div class="social-link">';
echo '<a href="#">';
echo '<i class="fa fa-google-plus"></i>';
echo '</a>';
echo '</div>';
echo '<!-- /SOCIAL LINK -->';
echo '</li>';
echo '<!-- ACTIONS LIST ITEM -->';
echo '';
echo '<!-- ACTIONS LIST ITEM -->';
echo '<li class="actions-list-item">';
echo '<!-- SOCIAL LINK -->';
echo '<div class="social-link">';
echo '<a href="#">';
echo '<i class="fa fa-rss"></i>';
echo '</a>';
echo '</div>';
echo '<!-- /SOCIAL LINK -->';
echo '</li>';
echo '<!-- ACTIONS LIST ITEM -->';
echo '';
echo '<!-- ACTIONS LIST ITEM -->';
echo '<li class="actions-list-item">';
echo '<!-- SOCIAL LINK -->';
echo '<div class="social-link">';
echo '<a href="#">';
echo '<i class="fa fa-vimeo"></i>';
echo '</a>';
echo '</div>';
echo '<!-- /SOCIAL LINK -->';
echo '</li>';
echo '<!-- ACTIONS LIST ITEM -->';
echo '</ul>';
echo '<!-- ACTIONS LIST -->';
echo '';
echo '<!-- ACTIONS LIST -->';
echo '<ul class="actions-list right">';
echo '<!-- ACTIONS LIST ITEM -->';
echo '<li class="actions-list-item">';
echo '<a class="action-button options-dropdown dropdown-control click-closable" href="#">';
echo '<span class="language-selected-option">eng</span>';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow small face-down">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</a>';
echo '';
echo '<!-- DROPDOWN LIST -->';
echo '<ul class="dropdown-list dropdown">';
echo '<li data-language="eng" class="dropdown-list-item language-option selected">';
echo '<a href="#">eng</a>';
echo '</li>';
echo '<li data-language="spa" class="dropdown-list-item language-option">';
echo '<a href="#">spa</a>';
echo '</li>';
echo '<li data-language="ger" class="dropdown-list-item language-option">';
echo '<a href="#">ger</a>';
echo '</li>';
echo '</ul>';
echo '<!-- /DROPDOWN LIST -->';
echo '</li>';
echo '<!-- ACTIONS LIST ITEM -->';
echo '';
echo '<!-- ACTIONS LIST ITEM -->';
echo '<li class="actions-list-item">';
echo '<a class="action-button options-dropdown dropdown-control click-closable" href="#">';
echo '<span class="currency-selected-option">usd</span>';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow small face-down">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</a>';
echo '';
echo '<!-- DROPDOWN LIST -->';
echo '<ul class="dropdown-list dropdown">';
echo '<li data-currency="usd" class="dropdown-list-item currency-option selected">';
echo '<a href="#">usd</a>';
echo '</li>';
echo '<li data-currency="euro" class="dropdown-list-item currency-option">';
echo '<a href="#">euro</a>';
echo '</li>';
echo '</ul>';
echo '<!-- /DROPDOWN LIST -->';
echo '</li>';
echo '<!-- ACTIONS LIST ITEM -->';
echo '';
echo '<!-- ACTIONS LIST ITEM -->';
echo '<li class="actions-list-item">';
echo '<a class="action-button" href="profile.php">My Account</a>';
echo '</li>';
echo '<!-- ACTIONS LIST ITEM -->';
echo '';
echo '<!-- ACTIONS LIST ITEM -->';
echo '<li class="actions-list-item">';
echo '<a class="action-button" href="wishlist.php">Wishlist<span class="bold">4</span></a>';
echo '</li>';
echo '<!-- ACTIONS LIST ITEM -->';
echo '';
echo '<!-- ACTIONS LIST ITEM -->';
echo '<li class="actions-list-item">';
echo '<a class="action-button" href="index.html">Logout</a>';
echo '</li>';
echo '<!-- ACTIONS LIST ITEM -->';
echo '';
echo '<!-- ACTIONS LIST ITEM -->';
echo '<li class="actions-list-item">';
echo '<!-- SEARCH FORM -->';
echo '<form class="search-form">';
echo '<input type="text" name="search" autocomplete="off" placeholder="Search products here...">';
echo '<!-- SEARCH SUBMIT -->';
echo '<div class="search-submit">';
echo '<!-- SVG MAG GLASS -->';
echo '<svg class="svg-mag-glass">';
echo '<use xlink:href="#svg-mag-glass"></use>';
echo '</svg>';
echo '<!-- /SVG MAG GLASS -->';
echo '</div>';
echo '<!-- /SEARCH SUBMIT -->';
echo '';
echo '<!-- SEARCH CANCEL -->';
echo '<div class="search-cancel hidden">';
echo '<!-- SVG CROSS -->';
echo '<svg class="svg-cross">';
echo '<use xlink:href="#svg-cross"></use>';
echo '</svg>';
echo '<!-- /SVG CROSS -->';
echo '</div>';
echo '<!-- /SEARCH CANCEL -->';
echo '</form>';
echo '<!-- /SEARCH FORM -->';
echo '</li>';
echo '<!-- ACTIONS LIST ITEM -->';
echo '</ul>';
echo '<!-- ACTIONS LIST -->';
echo '</div>';
echo '<!-- WIDGET LINE -->';
echo '</div>';
echo '<!-- WIDGET LINE WRAP -->';
echo '';
echo '<!-- WIDGET LINE WRAP -->';
echo '<div class="widget-line-wrap widget-line-2">';
echo '<!-- WIDGET LINE -->';
echo '<div class="widget-line">';
echo '<!-- ACTIONS LIST -->';
echo '<ul class="actions-list">';
echo '<!-- ACTIONS LIST ITEM -->';
echo '<li class="actions-list-item full void">';
echo '<!-- SEARCH FORM -->';
echo '<form class="search-form">';
echo '<input type="text" name="search" autocomplete="off" placeholder="Search products here...">';
echo '<!-- SEARCH SUBMIT -->';
echo '<div class="search-submit">';
echo '<!-- SVG MAG GLASS -->';
echo '<svg class="svg-mag-glass">';
echo '<use xlink:href="#svg-mag-glass"></use>';
echo '</svg>';
echo '<!-- /SVG MAG GLASS -->';
echo '</div>';
echo '<!-- /SEARCH SUBMIT -->';
echo '';
echo '<!-- SEARCH CANCEL -->';
echo '<div class="search-cancel hidden">';
echo '<!-- SVG CROSS -->';
echo '<svg class="svg-cross">';
echo '<use xlink:href="#svg-cross"></use>';
echo '</svg>';
echo '<!-- /SVG CROSS -->';
echo '</div>';
echo '<!-- /SEARCH CANCEL -->';
echo '</form>';
echo '<!-- /SEARCH FORM -->';
echo '</li>';
echo '<!-- ACTIONS LIST ITEM -->';
echo '</ul>';
echo '<!-- ACTIONS LIST -->';
echo '</div>';
echo '<!-- WIDGET LINE -->';
echo '</div>';
echo '<!-- WIDGET LINE WRAP -->';
echo '';
echo '<!-- NAVIGATION WRAP -->';
echo '<div class="navigation-wrap">';
echo '<!-- NAVIGATION -->';
echo '<nav class="navigation">';
echo '<!-- LOGO -->';
echo '<figure class="logo">';
echo '<img src="img/logo.png" alt="logo">';
echo '<figcaption>PC WORLDZ</figcaption>';
echo '</figure>';
echo '<!-- /LOGO -->';
echo '';
echo '<!-- CART DROPDOWN WRAP -->';
echo '<div class="cart-dropdown-wrap">';
echo '<!-- CART DROPDOWN CONTROL -->';
echo '<div class="cart-dropdown-control">';
echo '<!-- SVG CART -->';
echo '<svg class="svg-cart">';
echo '<use xlink:href="#svg-cart"></use>';
echo '</svg>';
echo '<!-- /SVG CART -->';
echo '';
echo '<!-- SVG CROSS -->';
echo '<svg class="svg-cross medium hidden">';
echo '<use xlink:href="#svg-cross"></use>';
echo '</svg>';
echo '<!-- /SVG CROSS -->';
echo '';
echo '<!-- CART ITEM QUANTITY -->';
echo '<div class="cart-item-quantity">';
echo '<p>3</p>';
echo '</div>';
echo '<!-- /CART ITEM QUANTITY -->';
echo '</div>';
echo '<!-- /CART DROPDOWN CONTROL -->';
echo '';
echo '<!-- CART DROPDOWN -->';
echo '<div class="cart-dropdown">';
echo '<!-- CART DROPDOWN ITEMS -->';
echo '<div class="cart-dropdown-items">';
echo '<!-- CART DROPDOWN ITEM -->';
echo '<div class="cart-dropdown-item">';
echo '<!-- PRODUCT IMG -->';
echo '<a href="product-page-v1.php">';
echo '<figure class="product-img small">';
echo '<img src="img/products/01.png" alt="02">';
echo '</figure>';
echo '</a>';
echo '<!-- /PRODUCT IMG -->';
echo '';
echo '<!-- CART DROPDOWN ITEM INFO -->';
echo '<div class="cart-dropdown-item-info">';
echo '<a href="product-page-v1.html"><h6 class="title small">';
?>          
              <?php
              $item = simplexml_load_file('data/Saludo-Peralta-Aquino_IT2F_PcWorldz.xml');
              echo $item->product[0]->name;
              ?>
              <?php
echo '</h6></a>';
echo '<p class="product-description small">Gaming</p>';
echo '<!-- RATING -->';
echo '<ul class="rating small">';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '</ul>';
echo '<!-- /RATING -->';
echo '<p class="product-quantity">x4</p>';
echo '<p class="product-price"><br><br>';
echo '₱233,848';
echo '</p>';
echo '</div>';
echo '<!-- /CART DROPDOWN ITEM INFO -->';
echo '';
echo '<!-- SVG CROSS -->';
echo '<svg class="svg-cross medium">';
echo '<use xlink:href="#svg-cross"></use>';
echo '</svg>';
echo '<!-- /SVG CROSS -->';
echo '</div>';
echo '<!-- /CART DROPDOWN ITEM -->';
echo '';
echo '<!-- CART DROPDOWN ITEM -->';
echo '<div class="cart-dropdown-item">';
echo '<!-- PRODUCT IMG -->';
echo '<a href="product-page-v1.php">';
echo '<figure class="product-img small">';
echo '<img src="img/products/02.png" alt="06">';
echo '</figure>';
echo '</a>';
echo '<!-- /PRODUCT IMG -->';
echo '';
echo '<!-- CART DROPDOWN ITEM INFO -->';
echo '<div class="cart-dropdown-item-info">';
echo '<a href="product-page-v1.html"><h6 class="title small">';
?>
              <?php
              $item = simplexml_load_file('data/Saludo-Peralta-Aquino_IT2F_PcWorldz.xml');
              echo $item->product[1]->name;
              ?>
              <?php
echo '</h6></a>';
echo '<p class="product-description small">Gaming</p>';
echo '<!-- RATING -->';
echo '<ul class="rating small">';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '</ul>';
echo '<!-- /RATING -->';
echo '<p class="product-quantity">x2</p>';
echo '<p class="product-price"><br><br>';
echo '₱57,032';
echo '</p>';
echo '</div>';
echo '<!-- /CART DROPDOWN ITEM INFO -->';
echo '';
echo '<!-- SVG CROSS -->';
echo '<svg class="svg-cross medium">';
echo '<use xlink:href="#svg-cross"></use>';
echo '</svg>';
echo '<!-- /SVG CROSS -->';
echo '</div>';
echo '<!-- /CART DROPDOWN ITEM -->';
echo '';
echo '<!-- CART DROPDOWN ITEM -->';
echo '<div class="cart-dropdown-item">';
echo '<!-- PRODUCT IMG -->';
echo '<a href="product-page-v1.php">';
echo '<figure class="product-img small">';
echo '<img src="img/products/03.png" alt="05">';
echo '</figure>';
echo '</a>';
echo '<!-- /PRODUCT IMG -->';
echo '';
echo '<!-- CART DROPDOWN ITEM INFO -->';
echo '<div class="cart-dropdown-item-info">';
echo '<a href="product-page-v1.html"><h6 class="title small">';
?>
              <?php
              $item = simplexml_load_file('data/Saludo-Peralta-Aquino_IT2F_PcWorldz.xml');
              echo $item->product[2]->name;
              ?>
               <?php
echo '</h6></a>';
echo '<p class="product-description small">Gaming</p>';
echo '<!-- RATING -->';
echo '<ul class="rating small">';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '</ul>';
echo '<!-- /RATING -->';
echo '<p class="product-quantity">x1</p>';
echo '<p class="product-price"> <br><br>';
?>
              <?php
              $item = simplexml_load_file('data/Saludo-Peralta-Aquino_IT2F_PcWorldz.xml');
              echo $item->product[2]->price;
              ?>
<?php
echo '</p>';
echo '</div>';
echo '<!-- /CART DROPDOWN ITEM INFO -->';
echo '';
echo '<!-- SVG CROSS -->';
echo '<svg class="svg-cross medium">';
echo '<use xlink:href="#svg-cross"></use>';
echo '</svg>';
echo '<!-- /SVG CROSS -->';
echo '</div>';
echo '<!-- /CART DROPDOWN ITEM -->';
echo '</div>';
echo '<!-- CART DROPDOWN ITEMS -->';
echo '';
echo '<!-- CART DROPDOWN SUBTOTAL -->';
echo '<div class="cart-dropdown-subtotal">';
echo '<p class="title small">Cart Subtotal</p>';
echo '<p class="product-price">₱303,827</p>';
echo '</div>';
echo '<!-- /CART DROPDOWN SUBTOTAL -->';
echo '';
echo '<!-- CART DROPDOWN ACTIONS -->';
echo '<div class="cart-dropdown-actions">';
echo '<a href="cart.php" class="button dark large">Go to the Cart</a>';
echo '<a href="identification.php" class="button large">Go to Checkout</a>';
echo '</div>';
echo '<!-- /CART DROPDOWN ACTIONS -->';
echo '</div>';
echo '<!-- /CART DROPDOWN -->';
echo '</div>';
echo '<!-- /CART DROPDOWN WRAP -->';
echo '';
echo '<!-- MAIN MENU -->';
echo '<ul class="main-menu">';
echo '<!-- MAIN MENU ITEM -->';
echo '<li class="main-menu-item">';
echo '<a href="index.php">Home</a>';
echo '</li>';
echo '<!-- /MAIN MENU ITEM -->';
echo '';
echo '<!-- MAIN MENU ITEM -->';
echo '<li class="main-menu-item">';
echo '<a href="aboutus.php">About</a>';
echo '</li>';
echo '<!-- /MAIN MENU ITEM -->';
echo '';
echo '<!-- MAIN MENU ITEM -->';
echo '<li class="main-menu-item">';
echo '<a href="shop-list.php">';
echo 'Shop';
echo '</a>';
echo '';
echo '<!-- MENU DROPDOWN -->';
echo '<ul class="menu-dropdown">';
echo '<!-- MENU DROPDOWN ITEM -->';
echo '<li class="menu-dropdown-item">';
echo '<a href="shop-list.php">Motherboards</a>';
echo '</li>';
echo '<li class="menu-dropdown-item">';
echo '<a href="shop-list2.php">Processors</a>';
echo '</li>';
echo '<li class="menu-dropdown-item">';
echo '<a href="shop-list3.php">Graphic Cards</a>';
echo '</li>';
echo '';
echo '</li>';
echo '';
echo '</ul>';
echo '<!-- /MENU DROPDOWN -->';
echo '</li>';
echo '<!-- /MAIN MENU ITEM -->';
echo '';
echo '<!-- MAIN MENU ITEM -->';
echo '<li class="main-menu-item">';
echo '<a href="blog.php">Our Blog</a>';
echo '</li>';
echo '<!-- /MAIN MENU ITEM -->';
echo '';
echo '<!-- MAIN MENU ITEM -->';
echo '<li class="main-menu-item sub">';
echo '<a href="#">';
echo 'Features';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow face-down">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</a>';
echo '';
echo '<!-- CONTENT DROPDOWN -->';
echo '<div class="content-dropdown with-bg">';
echo '';
echo '<!-- CONTENT DROPDOWN COLUMN -->';
echo '<div class="content-dropdown-column">';
echo '<h6 class="title tiny secondary">Account</h6>';
echo '<hr class="line-separator">';
echo '<!-- LINK LIST -->';
echo '<ul class="link-list simple">';
echo '<!-- LINK LIST ITEM -->';
echo '<li class="link-list-item">';
echo '<a href="identification.php">Identification</a>';
echo '</li>';
echo '<!-- /LINK LIST ITEM -->';
echo '';
echo '<!-- LINK LIST ITEM -->';
echo '<li class="link-list-item">';
echo '<a href="billing-shipping.php">Billing and Shipping</a>';
echo '</li>';
echo '<!-- /LINK LIST ITEM -->';
echo '';
echo '<!-- LINK LIST ITEM -->';
echo '<li class="link-list-item">';
echo '<a href="confirmation.php">Confirmation</a>';
echo '</li>';
echo '<!-- /LINK LIST ITEM -->';
echo '';
echo '<!-- LINK LIST ITEM -->';
echo '<li class="link-list-item">';
echo '<a href="cart.php">Shopping Cart</a>';
echo '</li>';
echo '<!-- /LINK LIST ITEM -->';
echo '';
echo '<!-- LINK LIST ITEM -->';
echo '<li class="link-list-item">';
echo '<a href="wishlist.php">Wishlist</a>';
echo '</li>';
echo '<!-- /LINK LIST ITEM -->';
echo '';
echo '<!-- LINK LIST ITEM -->';
echo '<li class="link-list-item">';
echo '<a href="profile.php">Your Account</a>';
echo '</li>';
echo '<!-- /LINK LIST ITEM -->';
echo '</ul>';
echo '<!-- /LINK LIST -->';
echo '</div>';
echo '<!-- /CONTENT DROPDOWN COLUMN -->';
echo '</div>';
echo '<!-- /CONTENT DROPDOWN -->';
echo '</li>';
echo '<!-- /MAIN MENU ITEM -->';
echo '';
echo '<!-- MAIN MENU ITEM -->';
echo '<li class="main-menu-item">';
echo '<a href="contactus.php">Contact</a>';
echo '</li>';
echo '<!-- /MAIN MENU ITEM -->';
echo '</ul>';
echo '<!-- /MAIN MENU -->';
echo '</nav>';
echo '<!-- /NAVIGATION -->';
echo '</div>';
echo '<!-- /NAVIGATION WRAP -->';
echo '';
echo '<!-- MOBILE MENU WRAP -->';
echo '<div class="mobile-menu-wrap">';
echo '<!-- MOBILE MENU CONTROL -->';
echo '<div class="mobile-menu-control dropdown-control">';
echo '<!-- SVG BURGER -->';
echo '<svg class="svg-burger">';
echo '<use xlink:href="#svg-burger"></use>';
echo '</svg>';
echo '<!-- /SVG BURGER -->';
echo '</div>';
echo '<!-- /MOBILE MENU CONTROL -->';
echo '';
echo '<!-- MOBILE MENU -->';
echo '<ul class="mobile-menu dropdown">';
echo '<!-- MOBILE MENU ITEM -->';
echo '<li class="mobile-menu-item">';
echo '<a href="index.php">Home</a>';
echo '</li>';
echo '<!-- /MOBILE MENU ITEM -->';
echo '';
echo '<!-- MOBILE MENU ITEM -->';
echo '<li class="mobile-menu-item">';
echo '<a href="aboutus.php">About</a>';
echo '</li>';
echo '<!-- /MOBILE MENU ITEM -->';
echo '';
echo '<!-- MOBILE MENU ITEM -->';
echo '<li class="mobile-menu-item">';
echo '<a href="#" class="dropdown-control">';
echo 'Shop';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow medium rotable">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</a>';
echo '';
echo '<!-- MOBILE MENU DROPDOWN -->';
echo '<ul class="mobile-menu-dropdown dropdown">';
echo '';
echo '<li class="mobile-menu-dropdown-item">';
echo '<a href="shop-sidebar-list.php">Motherboards</a>';
echo '</li>';
echo '<li class="mobile-menu-dropdown-item">';
echo '<a href="shop-sidebar-list.php">Processors</a>';
echo '</li>';
echo '<li class="mobile-menu-dropdown-item">';
echo '<a href="shop-sidebar-list.php">Graphic Cards</a>';
echo '</li>';
echo '';
echo '</ul>';
echo '<!-- /MOBILE MENU DROPDOWN -->';
echo '</li>';
echo '<!-- /MOBILE MENU ITEM -->';
echo '';
echo '<!-- MOBILE MENU ITEM -->';
echo '<li class="mobile-menu-item">';
echo '<a href="blog.php">Our Blog</a>';
echo '</li>';
echo '<!-- /MOBILE MENU ITEM -->';
echo '';
echo '<!-- MOBILE MENU ITEM -->';
echo '<li class="mobile-menu-item">';
echo '<a href="#" class="dropdown-control">';
echo 'Features';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow medium rotable">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</a>';
echo '';
echo '<!-- MOBILE MENU DROPDOWN -->';
echo '<ul class="mobile-menu-dropdown dropdown">';
echo '';
echo '<!-- MOBILE MENU DROPDOWN ITEM -->';
echo '<li class="mobile-menu-dropdown-item">';
echo '<a href="aboutus.php">asdf</a>';
echo '</li>';
echo '';
echo '<!-- MOBILE MENU DROPDOWN ITEM -->';
echo '<li class="mobile-menu-dropdown-item">';
echo '<a href="identification.php">Identification</a>';
echo '</li>';
echo '<!-- /MOBILE MENU DROPDOWN ITEM -->';
echo '';
echo '<!-- MOBILE MENU DROPDOWN ITEM -->';
echo '<li class="mobile-menu-dropdown-item">';
echo '<a href="billing-shipping.php">Billing and Shipping</a>';
echo '</li>';
echo '<!-- /MOBILE MENU DROPDOWN ITEM -->';
echo '';
echo '<!-- MOBILE MENU DROPDOWN ITEM -->';
echo '<li class="mobile-menu-dropdown-item">';
echo '<a href="confirmation.php">Confirmation</a>';
echo '</li>';
echo '<!-- /MOBILE MENU DROPDOWN ITEM -->';
echo '';
echo '<!-- MOBILE MENU DROPDOWN ITEM -->';
echo '<li class="mobile-menu-dropdown-item">';
echo '<a href="cart.php">Shopping Cart</a>';
echo '</li>';
echo '<!-- /MOBILE MENU DROPDOWN ITEM -->';
echo '';
echo '<!-- MOBILE MENU DROPDOWN ITEM -->';
echo '<li class="mobile-menu-dropdown-item">';
echo '<a href="wishlist.php">Wishlist</a>';
echo '</li>';
echo '<!-- /MOBILE MENU DROPDOWN ITEM -->';
echo '';
echo '<!-- MOBILE MENU DROPDOWN ITEM -->';
echo '<li class="mobile-menu-dropdown-item">';
echo '<a href="profile.php">Your Account</a>';
echo '</li>';
echo '<!-- /MOBILE MENU DROPDOWN ITEM -->';
echo '</ul>';
echo '<!-- /MOBILE MENU DROPDOWN -->';
echo '</li>';
echo '<!-- /MOBILE MENU ITEM -->';
echo '';
echo '<!-- MOBILE MENU ITEM -->';
echo '<li class="mobile-menu-item">';
echo '<a href="contactus.php">Contact</a>';
echo '</li>';
echo '<!-- /MOBILE MENU ITEM -->';
echo '';
echo '<!-- MOBILE MENU ITEM -->';
echo '<li class="mobile-menu-item">';
echo '<a href="profile.php">My Account</a>';
echo '</li>';
echo '<!-- /MOBILE MENU ITEM -->';
echo '';
echo '<!-- MOBILE MENU ITEM -->';
echo '<li class="mobile-menu-item">';
echo '<a href="wishlist.php">';
echo 'Wishlist';
echo '<span class="bold">4</span>';
echo '</a>';
echo '</li>';
echo '<!-- /MOBILE MENU ITEM -->';
echo '';
echo '<!-- MOBILE MENU ITEM -->';
echo '<li class="mobile-menu-item">';
echo '<a href="#" class="dropdown-control">';
echo 'Language:';
echo '<span class="selected-option language-selected-option">eng</span>';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow medium rotable">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</a>';
echo '';
echo '<!-- MOBILE MENU DROPDOWN -->';
echo '<ul class="mobile-menu-dropdown dropdown">';
echo '<!-- MOBILE MENU DROPDOWN ITEM -->';
echo '<li data-language="eng" class="mobile-menu-dropdown-item language-option selected">';
echo '<a href="#">eng</a>';
echo '</li>';
echo '<!-- /MOBILE MENU DROPDOWN ITEM -->';
echo '';
echo '<!-- MOBILE MENU DROPDOWN ITEM -->';
echo '<li data-language="spa" class="mobile-menu-dropdown-item language-option">';
echo '<a href="#">spa</a>';
echo '</li>';
echo '<!-- /MOBILE MENU DROPDOWN ITEM -->';
echo '';
echo '<!-- MOBILE MENU DROPDOWN ITEM -->';
echo '<li data-language="ger" class="mobile-menu-dropdown-item language-option">';
echo '<a href="#">ger</a>';
echo '</li>';
echo '<!-- /MOBILE MENU DROPDOWN ITEM -->';
echo '</ul>';
echo '<!-- /MOBILE MENU DROPDOWN -->';
echo '</li>';
echo '<!-- /MOBILE MENU ITEM -->';
echo '';
echo '<!-- MOBILE MENU ITEM -->';
echo '<li class="mobile-menu-item">';
echo '<a href="#" class="dropdown-control">';
echo 'Currency:';
echo '<span class="selected-option currency-selected-option">usd</span>';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow medium rotable">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</a>';
echo '';
echo '<!-- MOBILE MENU DROPDOWN -->';
echo '<ul class="mobile-menu-dropdown dropdown">';
echo '<!-- MOBILE MENU DROPDOWN ITEM -->';
echo '<li data-currency="usd" class="mobile-menu-dropdown-item currency-option selected">';
echo '<a href="#">usd</a>';
echo '</li>';
echo '<!-- /MOBILE MENU DROPDOWN ITEM -->';
echo '';
echo '<!-- MOBILE MENU DROPDOWN ITEM -->';
echo '<li data-currency="euro" class="mobile-menu-dropdown-item currency-option">';
echo '<a href="#">euro</a>';
echo '</li>';
echo '<!-- /MOBILE MENU DROPDOWN ITEM -->';
echo '</ul>';
echo '<!-- /MOBILE MENU DROPDOWN -->';
echo '</li>';
echo '<!-- /MOBILE MENU ITEM -->';
echo '';
echo '<!-- MOBILE MENU ITEM -->';
echo '<li class="mobile-menu-item void">';
echo '<a href="#">Logout</a>';
echo '</li>';
echo '<!-- /MOBILE MENU ITEM -->';
echo '</ul>';
echo '<!-- /MOBILE MENU -->';
echo '</div>';
echo '<!-- /MOBILE MENU WRAP -->';
echo '';
echo '<!-- SECTION NAVIGATION WRAP -->';
echo '<div class="section-navigation-wrap">';
echo '<!-- SECTION NAVIGATION -->';
echo '<div class="section-navigation">';
echo '<!-- SECTION NAVIGATION PATH -->';
echo '<p class="section-navigation-path">';
echo '<span class="path">Home</span>';
echo '<span class="path">';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow tiny">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</span>';
echo '<span class="path">Browse All</span>';
echo '<span class="path bold">';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow tiny">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</span>';
echo '<span class="path current">Items</span>';
echo '</p>';
echo '<!-- SECTION NAVIGATION PATH -->';
echo '</div>';
echo '<!-- /SECTION NAVIGATION -->';
echo '</div>';
echo '<!-- /SECTION NAVIGATION WRAP -->';
echo '';
echo '<!-- SECTION WRAP -->';
echo '<div class="section-wrap">';
echo '<!-- SECTION -->';
echo '<div class="section bottom-void no-title">';
echo '<!-- PRODUCT VIEW -->';
echo '<div class="product-view full">';
echo '<!-- PRODUCT IMG LIST -->';
echo '<div class="product-img-list vertical border-anim">';
echo '<!-- PRODUCT IMG LIST ITEM -->';
echo '<div class="product-img-list-item selected">';
echo '<div class="overlay"></div>';
echo '<!-- PRODUCT IMG -->';
echo '<figure class="product-img small">';
echo '<img src="img/products/01.png" alt="product02">';
echo '</figure>';
echo '<!-- /PRODUCT IMG -->';
echo '</div>';
echo '<!-- /PRODUCT IMG LIST ITEM -->';
echo '';
echo '<!-- PRODUCT IMG LIST ITEM -->';
echo '<div class="product-img-list-item">';
echo '<div class="overlay"></div>';
echo '<!-- PRODUCT IMG -->';
echo '<figure class="product-img small">';
echo '<img src="img/products/02.png" alt="product06">';
echo '</figure>';
echo '<!-- /PRODUCT IMG -->';
echo '</div>';
echo '<!-- /PRODUCT IMG LIST ITEM -->';
echo '';
echo '<!-- PRODUCT IMG LIST ITEM -->';
echo '<div class="product-img-list-item">';
echo '<div class="overlay"></div>';
echo '<!-- PRODUCT IMG -->';
echo '<figure class="product-img small">';
echo '<img src="img/products/03.png" alt="product10">';
echo '</figure>';
echo '<!-- /PRODUCT IMG -->';
echo '</div>';
echo '<!-- /PRODUCT IMG LIST ITEM -->';
echo '';
echo '<!-- PRODUCT IMG LIST ITEM -->';
echo '<div class="product-img-list-item">';
echo '<div class="overlay"></div>';
echo '<!-- PRODUCT IMG -->';
echo '<figure class="product-img small">';
echo '<img src="img/products/04.png" alt="product08">';
echo '</figure>';
echo '<!-- /PRODUCT IMG -->';
echo '</div>';
echo '<!-- /PRODUCT IMG LIST ITEM -->';
echo '</div>';
echo '<!-- /PRODUCT IMG LIST -->';
echo '';
echo '<!-- PRODUCT IMG -->';
echo '<figure class="product-img big scalable">';
echo '<img src="img/products/01.png" alt="product02">';
echo '</figure>';
echo '<!-- /PRODUCT IMG -->';
echo '';
echo '<!-- PRODUCT DETAILS -->';
echo '<div class="product-details">';
echo '<h2 class="title bigger">';
?>           
              <?php
              $item = simplexml_load_file('data/Saludo-Peralta-Aquino_IT2F_PcWorldz.xml');
              echo $item->product[0]->name;
              ?>
         <?php
echo '</h2>';
echo '<p class="product-description medium">Gaming</p>';
echo '<!-- RATING -->';
echo '<ul class="rating medium">';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '</ul>';
echo '<!-- /RATING -->';
echo '<h6 class="product-price big">';
?>
            <?php
              $item = simplexml_load_file('data/Saludo-Peralta-Aquino_IT2F_PcWorldz.xml');
              echo $item->product[0]->price;
              ?>
</h6>
          <p class="product-description-preview">              <?php
              $item = simplexml_load_file('data/Saludo-Peralta-Aquino_IT2F_PcWorldz.xml');
              echo $item->product[0]->description;
              ?>
</p>

          <!-- FORM -->
          <?php
echo '<form>';
echo '<!-- FORM ROW -->';
echo '<div class="form-row">';
echo '<label class="rl-label">Size</label>';
echo '<!-- SELECT BLOCK -->';
echo '<label for="helmet_size" class="select-block medium">';
echo '<select name="helmet_size" id="helmet_size">';
echo '<option value="0">Small</option>';
echo '<option value="1" selected>Medium</option>';
echo '<option value="2">Big</option>';
echo '</select>';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow face-down">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</label>';
echo '<!-- SELECT BLOCK -->';
echo '</div>';
echo '<!-- /FORM ROW -->';
echo '';
echo '<!-- FORM ROW -->';
echo '<div class="form-row">';
echo '<label class="rl-label">Base Color</label>';
echo '<!-- SELECT BLOCK -->';
echo '<label for="helmet_color" class="select-block medium">';
echo '<select name="helmet_color" id="helmet_color">';
echo '<option value="0">Green</option>';
echo '<option value="1">Blue</option>';
echo '<option value="2">Black</option>';
echo '</select>';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow face-down">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</label>';
echo '<!-- SELECT BLOCK -->';
echo '</div>';
echo '<!-- /FORM ROW -->';
echo '';
echo '<!-- FORM ROW -->';
echo '<div class="form-row">';
echo '<label class="rl-label">Quantity</label>';
echo '<!-- QUANTITY INPUT -->';
echo '<div class="quantity-input">';
echo '<span class="count">4</span>';
echo '<!-- INCREMENT COUNT -->';
echo '<div class="increment-count">';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow face-up">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</div>';
echo '<!-- /INCREMENT COUNT -->';
echo '';
echo '<!-- DECREMENT COUNT -->';
echo '<div class="decrement-count">';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow face-down">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</div>';
echo '<!-- /DECREMENT COUNT -->';
echo '</div>';
echo '<!-- QUANTITY INPUT -->';
echo '</div>';
echo '<!-- /FORM ROW -->';
echo '</form>';
echo '<!-- /FORM -->';
echo '';
echo '<!-- PRODUCT DETAILS ACTIONS -->';
echo '<div class="product-details-actions">';
echo '<a href="#" class="button medium cart-icon">';
echo '<!-- SVG CART -->';
echo '<svg class="svg-cart">';
echo '<use xlink:href="#svg-cart"></use>';
echo '</svg>';
echo '<!-- /SVG CART -->';
echo 'Add to Cart';
echo '</a>';
echo '<!-- BUTTON LIST -->';
echo '<div class="button-list wrap-3">';
echo '<!-- BUTTON -->';
echo '<a href="#" class="button square">';
echo '<!-- SVG HEART -->';
echo '<svg class="svg-heart">';
echo '<use xlink:href="#svg-heart"></use>';
echo '</svg>';
echo '<!-- /SVG HEART -->';
echo '</a>';
echo '<!-- /BUTTON -->';
echo '';
echo '<!-- BUTTON -->';
echo '<a href="#" class="button square">';
echo '<i class="fa fa-facebook"></i>';
echo '</a>';
echo '<!-- /BUTTON -->';
echo '';
echo '<!-- BUTTON -->';
echo '<a href="#" class="button square">';
echo '<i class="fa fa-twitter"></i>';
echo '</a>';
echo '<!-- /BUTTON -->';
echo '</div>';
echo '<!-- /BUTTON LIST -->';
echo '</div>';
echo '<!-- /PRODUCT DETAILS ACTIONS -->';
echo '</div>';
echo '<!-- /PRODUCT DETAILS -->';
echo '</div>';
echo '<!-- /PRODUCT VIEW -->';
echo '</div>';
echo '<!-- /SECTION -->';
echo '</div>';
echo '<!-- /SECTION WRAP -->';
echo '';
echo '<!-- SECTION WRAP -->';
echo '<div class="section-wrap">';
echo '<!-- SECTION -->';
echo '<div class="section bottom-void">';
echo '<!-- TABBED CONTENT -->';
echo '<div class="tabbed-content centered short">';
echo '<!-- TABBED CONTENT HEADER -->';
echo '<div class="tabbed-content-header">';
echo '<h6 class="title tabbed-content-item-title tab-control selected">';
echo 'Description';
echo '<span class="triangle"></span>';
echo '</h6>';
echo '<h6 class="title tabbed-content-item-title tab-control ">';
echo 'Reviews';
echo '<span class="triangle"></span>';
echo '</h6>';
echo '</div>';
echo '<!-- /TABBED CONTENT HEADER -->';
echo '<div class="tab-separator"></div>';
echo '';
echo '<!-- TABBED CONTENT ITEM -->';
echo '<div class="tabbed-content-item tab-item padded">';
echo '<!-- TEXT ROW -->';
echo '<div class="text-row">';
echo '<h2 class="title main-title">Enjoy all Gaming PC parts!</h2>';
echo '<p>By building your own Computer you gain a lot of insight into the inner workings of Hardware Components and how everything fits together.';
echo '<br>';
echo 'You will be able to troubleshoot if any problems arise later on much easier, than when you have no clue what is actually going on inside your PC’s Case.';
echo '<br>';
echo 'Knowing the ins and outs of assembling a Computer and what Parts a Computer needs will also let you upgrade your Computer in the future.';
echo '<br>';
echo 'Another very important factor is optimization. Knowing how a Computer works, enables you to optimize it as much as possible for your type of work.';
echo '<br>';
echo 'You can optimize by buying the best parts for your specific workloads, be it Gaming, 3D Rendering, Modeling, Graphic Design, Video Editing or so many other purposes you can use a Computer for.';
echo '<br>';
echo 'Building your own computer also is a lot cheaper than getting a pre-built PC. You can usually save around 30% in Cost when researching, buying the PC Components individually, and assembling them yourself.';
echo '<br>';
echo 'And the best of it all, building a Computer is so easy, it’s kind of interesting that not more people are doing it!';
echo '<br>';
echo 'Anyway, we now definitely know that we are on the right track by looking into building our own Computer, that’s probably why you came here in the first place.</p>';
echo '</div>';
echo '<!-- /TEXT ROW -->';
echo '';
echo '<!-- TEXT ROW -->';
echo '<div class="text-row">';
echo '<h2 class="title subtitle">Computer Parts List</h2>';
echo '<p>Case, Motherboard, CPU [Processor], GPU [Graphics Card] (if no integrated GPU), RAM [Memory], Storage Device (SSD, NVME SSD, HDD), Cooling (CPU, Chassis), PSU [Power Supply Unit], Display device, Monitor, Operating System [OS], Input Devices, Mouse, Keyboard';
echo '</p>';
echo '</div>';
echo '<!-- /TEXT ROW -->';
echo '';
echo '<!-- FEATURE ENUM -->';
echo '<div class="feature-enum">';
echo '<!-- FEATURE ENUM ITEM -->';
echo '<div class="feature-enum-item">';
echo '<i class="s-icon icon-badge"></i>';
echo '<h6 class="title">Quality Assurance</h6>';
echo '<p>We will make sure to give you the best qualities of PC products.</p>';
echo '</div>';
echo '<!-- FEATURE ENUM ITEM -->';
echo '';
echo '<div class="separator"></div>';
echo '';
echo '<!-- FEATURE ENUM ITEM -->';
echo '<div class="feature-enum-item">';
echo '<i class="s-icon icon-rocket"></i>';
echo '<h6 class="title">Overnight Shipping</h6>';
echo '<p>We ship our product as fast as possible.</p>';
echo '</div>';
echo '<!-- FEATURE ENUM ITEM -->';
echo '</div>';
echo '<!-- /FEATURE ENUM -->';
echo '</div>';
echo '<!-- /TABBED CONTENT ITEM -->';
echo '';
echo '<!-- TABBED CONTENT ITEM -->';
echo '<div class="tabbed-content-item tab-item padded hidden">';
echo '<!-- REVIEWS -->';
echo '<div class="reviews">';
echo '<!-- REVIEWS HEADER -->';
echo '<div class="reviews-header">';
echo '<h2 class="title"><span class="bold">4</span> Reviews</h2>';
echo '<p class="title review-title">3 out of 5</p>';
echo '<!-- RATING -->';
echo '<ul class="rating medium">';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '</ul>';
echo '<!-- /RATING -->';
echo '<a href="#review-popup" class="button popup-trigger">Write a Review</a>';
echo '</div>';
echo '<!-- /REVIEWS HEADER -->';
echo '';
echo '<!-- REVIEWS ITEM -->';
echo '<div class="reviews-item">';
echo '<p class="title review-title">Truly Works of Art!</p>';
echo '<!-- RATING -->';
echo '<ul class="rating">';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '</ul>';
echo '<!-- /RATING -->';
echo '<p><span class="review-author">Jessica March -</span> Thank you for giving us the best quality products.</p>';
echo '<p class="timestamp">3 weeks ago - <a href="#">Report</a></p>';
echo '</div>';
echo '<!-- /REVIEWS ITEM -->';
echo '';
echo '<!-- REVIEWS ITEM -->';
echo '<div class="reviews-item">';
echo '<p class="title review-title">Comfort and Design</p>';
echo '<!-- RATING -->';
echo '<ul class="rating">';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '</ul>';
echo '<!-- /RATING -->';
echo '<p><span class="review-author">Steven Richards -</span> Thank you for giving us the best quality products.</p>';
echo '<p class="timestamp">4 weeks ago - <a href="#">Report</a></p>';
echo '</div>';
echo '<!-- /REVIEWS ITEM -->';
echo '';
echo '<!-- REVIEWS ITEM -->';
echo '<div class="reviews-item">';
echo '<p class="title review-title">Incredible Shipping</p>';
echo '<!-- RATING -->';
echo '<ul class="rating">';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '</ul>';
echo '<!-- /RATING -->';
echo '<p><span class="review-author">Spencer Jameson -</span> LThank you for giving us the best quality products.</p>';
echo '<p class="timestamp">1 month ago - <a href="#">Report</a></p>';
echo '</div>';
echo '<!-- /REVIEWS ITEM -->';
echo '';
echo '<!-- REVIEWS ITEM -->';
echo '<div class="reviews-item">';
echo '<p class="title review-title">First but not Last!</p>';
echo '<!-- RATING -->';
echo '<ul class="rating">';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '</ul>';
echo '<!-- /RATING -->';
echo '<p><span class="review-author">Marissa Roschers -</span> Thank you for giving us the best quality products.</p>';
echo '<p class="timestamp">2 years ago - <a href="#">Report</a></p>';
echo '</div>';
echo '<!-- /REVIEWS ITEM -->';
echo '</div>';
echo '<!-- /REVIEWS -->';
echo '</div>';
echo '<!-- /TABBED CONTENT ITEM -->';
echo '<div class="tab-separator"></div>';
echo '</div>';
echo '<!-- /TABBED CONTENT -->';
echo '</div>';
echo '<!-- /SECTION -->';
echo '</div>';
echo '<!-- /SECTION WRAP -->';
echo '';
echo '<!-- SECTION WRAP -->';
echo '<div class="section-wrap">';
echo '<!-- SECTION -->';
echo '<div class="section bottom-short">';
echo '<h6 class="pretitle">Check out Other</h6>';
echo '<h3 class="title large">Featured Products</h3>';
echo '<hr class="line-separator">';
echo '';
echo '<!-- PRODUCT LIST -->';
echo '<div class="product-list column-3-wrap">';
echo '<!-- PRODUCT LIST ITEM -->';
echo '<div class="product-list-item column">';
echo '<!-- PRODUCT LIST ITEM PREVIEW -->';
echo '<div class="product-list-item-preview">';
echo '<!-- PRODUCT IMG -->';
echo '<figure class="product-img">';
echo '<img src="img/products/05.png" alt="product01">';
echo '</figure>';
echo '<!-- /PRODUCT IMG -->';
echo '';
echo '<!-- PRODUCT LIST ITEM ACTIONS -->';
echo '<div class="product-list-item-actions">';
echo '<!-- BUTTON LIST -->';
echo '<div class="button-list wrap-4">';
echo '<!-- BUTTON -->';
echo '<a href="#" class="button square">';
echo '<!-- SVG CART -->';
echo '<svg class="svg-cart-small">';
echo '<use xlink:href="#svg-cart-small"></use>';
echo '</svg>';
echo '<!-- /SVG CART -->';
echo '</a>';
echo '<!-- /BUTTON -->';
echo '';
echo '<!-- BUTTON -->';
echo '<a href="#" class="button square">';
echo '<!-- SVG HEART -->';
echo '<svg class="svg-heart">';
echo '<use xlink:href="#svg-heart"></use>';
echo '</svg>';
echo '<!-- /SVG HEART -->';
echo '</a>';
echo '<!-- /BUTTON -->';
echo '';
echo '<!-- BUTTON -->';
echo '<a href="#" class="button square">';
echo '<i class="fa fa-facebook"></i>';
echo '</a>';
echo '<!-- /BUTTON -->';
echo '';
echo '<!-- BUTTON -->';
echo '<a href="#" class="button square">';
echo '<i class="fa fa-twitter"></i>';
echo '</a>';
echo '<!-- /BUTTON -->';
echo '</div>';
echo '<!-- /BUTTON LIST -->';
echo '</div>';
echo '<!-- /PRODUCT LIST ITEM ACTIONS -->';
echo '</div>';
echo '<!-- /PRODUCT LIST ITEM PREVIEW -->';
echo '';
echo '<!-- PRODUCT LIST ITEM INFO -->';
echo '<div class="product-list-item-info">';
echo '<a href="product-page-v1.html"><h6 class="title">';
?>
              <?php
              $item = simplexml_load_file('data/Saludo-Peralta-Aquino_IT2F_PcWorldz.xml');
              echo $item->product[4]->name;
              ?>
              <?php
echo '</h6></a>';
echo '<p class="product-description">Gaming</p>';
echo '<!-- PRODUCT LIST ITEM PRICE -->';
echo '<div class="product-list-item-price">';
echo '<!-- RATING -->';
echo '<ul class="rating">';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '</ul>';
echo '<!-- /RATING -->';
echo '<h6 class="product-price">';
?>
              <?php
              $item = simplexml_load_file('data/Saludo-Peralta-Aquino_IT2F_PcWorldz.xml');
              echo $item->product[4]->price;
              ?>
<?php
echo '</h6>';
echo '</div>';
echo '<!-- /PRODUCT LIST ITEM PRICE -->';
echo '</div>';
echo '<!-- /PRODUCT LIST ITEM INFO -->';
echo '</div>';
echo '<!-- /PRODUCT LIST ITEM -->';
echo '';
echo '<!-- PRODUCT LIST ITEM -->';
echo '<div class="product-list-item column">';
echo '<!-- PRODUCT LIST ITEM PREVIEW -->';
echo '<div class="product-list-item-preview">';
echo '<!-- PRODUCT IMG -->';
echo '<figure class="product-img">';
echo '<img src="img/products/06.png" alt="product02">';
echo '</figure>';
echo '<!-- /PRODUCT IMG -->';
echo '';
echo '<!-- PRODUCT LIST ITEM ACTIONS -->';
echo '<div class="product-list-item-actions">';
echo '<!-- BUTTON LIST -->';
echo '<div class="button-list wrap-4">';
echo '<!-- BUTTON -->';
echo '<a href="#" class="button square">';
echo '<!-- SVG CART -->';
echo '<svg class="svg-cart-small">';
echo '<use xlink:href="#svg-cart-small"></use>';
echo '</svg>';
echo '<!-- /SVG CART -->';
echo '</a>';
echo '<!-- /BUTTON -->';
echo '';
echo '<!-- BUTTON -->';
echo '<a href="#" class="button square">';
echo '<!-- SVG HEART -->';
echo '<svg class="svg-heart">';
echo '<use xlink:href="#svg-heart"></use>';
echo '</svg>';
echo '<!-- /SVG HEART -->';
echo '</a>';
echo '<!-- /BUTTON -->';
echo '';
echo '<!-- BUTTON -->';
echo '<a href="#" class="button square">';
echo '<i class="fa fa-facebook"></i>';
echo '</a>';
echo '<!-- /BUTTON -->';
echo '';
echo '<!-- BUTTON -->';
echo '<a href="#" class="button square">';
echo '<i class="fa fa-twitter"></i>';
echo '</a>';
echo '<!-- /BUTTON -->';
echo '</div>';
echo '<!-- /BUTTON LIST -->';
echo '</div>';
echo '<!-- /PRODUCT LIST ITEM ACTIONS -->';
echo '</div>';
echo '<!-- /PRODUCT LIST ITEM PREVIEW -->';
echo '';
echo '<!-- PRODUCT LIST ITEM INFO -->';
echo '<div class="product-list-item-info">';
?>
            <a href="product-page-v1.html"><h6 class="title">
              <?php
              $item = simplexml_load_file('data/Saludo-Peralta-Aquino_IT2F_PcWorldz.xml');
              echo $item->product[5]->name;
              ?>
              <?php
echo '</h6></a>';
echo '<p class="product-description">Gaming</p>';
echo '<!-- PRODUCT LIST ITEM PRICE -->';
echo '<div class="product-list-item-price">';
echo '<!-- RATING -->';
echo '<ul class="rating">';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '</ul>';
echo '<!-- /RATING -->';
echo '<h6 class="product-price">';
?>
                <?php
              $item = simplexml_load_file('data/Saludo-Peralta-Aquino_IT2F_PcWorldz.xml');
              echo $item->product[5]->price;
              ?>
              <?php
echo '</h6>';
echo '</div>';
echo '<!-- /PRODUCT LIST ITEM PRICE -->';
echo '</div>';
echo '<!-- /PRODUCT LIST ITEM INFO -->';
echo '</div>';
echo '<!-- /PRODUCT LIST ITEM -->';
echo '';
echo '<!-- PRODUCT LIST ITEM -->';
echo '<div class="product-list-item column">';
echo '<!-- PRODUCT LIST ITEM PREVIEW -->';
echo '<div class="product-list-item-preview">';
echo '<!-- PRODUCT IMG -->';
echo '<figure class="product-img">';
echo '<img src="img/products/07.png" alt="product03">';
echo '</figure>';
echo '<!-- /PRODUCT IMG -->';
echo '';
echo '<!-- PRODUCT LIST ITEM ACTIONS -->';
echo '<div class="product-list-item-actions">';
echo '<!-- BUTTON LIST -->';
echo '<div class="button-list wrap-4">';
echo '<!-- BUTTON -->';
echo '<a href="#" class="button square">';
echo '<!-- SVG CART -->';
echo '<svg class="svg-cart-small">';
echo '<use xlink:href="#svg-cart-small"></use>';
echo '</svg>';
echo '<!-- /SVG CART -->';
echo '</a>';
echo '<!-- /BUTTON -->';
echo '';
echo '<!-- BUTTON -->';
echo '<a href="#" class="button square">';
echo '<!-- SVG HEART -->';
echo '<svg class="svg-heart">';
echo '<use xlink:href="#svg-heart"></use>';
echo '</svg>';
echo '<!-- /SVG HEART -->';
echo '</a>';
echo '<!-- /BUTTON -->';
echo '';
echo '<!-- BUTTON -->';
echo '<a href="#" class="button square">';
echo '<i class="fa fa-facebook"></i>';
echo '</a>';
echo '<!-- /BUTTON -->';
echo '';
echo '<!-- BUTTON -->';
echo '<a href="#" class="button square">';
echo '<i class="fa fa-twitter"></i>';
echo '</a>';
echo '<!-- /BUTTON -->';
echo '</div>';
echo '<!-- /BUTTON LIST -->';
echo '</div>';
echo '<!-- /PRODUCT LIST ITEM ACTIONS -->';
echo '</div>';
echo '<!-- /PRODUCT LIST ITEM PREVIEW -->';
echo '';
echo '<!-- PRODUCT LIST ITEM INFO -->';
echo '<div class="product-list-item-info">';
echo '<a href="product-page-v1.html"><h6 class="title">';
?>
              <?php
              $item = simplexml_load_file('data/Saludo-Peralta-Aquino_IT2F_PcWorldz.xml');
              echo $item->product[6]->name;
              ?>
              <?php
echo '</h6></a>';
echo '<p class="product-description">Gaming</p>';
echo '<!-- PRODUCT LIST ITEM PRICE -->';
echo '<div class="product-list-item-price">';
echo '<!-- RATING -->';
echo '<ul class="rating">';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item filled">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '';
echo '<!-- RATING ITEM -->';
echo '<li class="rating-item">';
echo '<!-- SVG STAR -->';
echo '<svg class="svg-star">';
echo '<use xlink:href="#svg-star"></use>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '</li>';
echo '<!-- /RATING ITEM -->';
echo '</ul>';
echo '<!-- /RATING -->';
echo '<h6 class="product-price">';
?>
                <?php
              $item = simplexml_load_file('data/Saludo-Peralta-Aquino_IT2F_PcWorldz.xml');
              echo $item->product[6]->price;
              ?>
              <?php
echo '</h6>';
echo '</div>';
echo '<!-- /PRODUCT LIST ITEM PRICE -->';
echo '</div>';
echo '<!-- /PRODUCT LIST ITEM INFO -->';
echo '</div>';
echo '<!-- /PRODUCT LIST ITEM -->';
echo '</div>';
echo '<!-- /PRODUCT LIST -->';
echo '</div>';
echo '<!-- /SECTION -->';
echo '</div>';
echo '<!-- /SECTION WRAP -->';
echo '';
echo '<!-- FOOTER WRAP -->';
echo '<footer class="footer-wrap">';
echo '<!-- FOOTER TOP -->';
echo '<div class="footer-top">';
echo '<!-- ABOUTUS PREVIEW -->';
echo '<div class="aboutus-preview">';
echo '<!-- LOGO -->';
echo '<figure class="logo">';
echo '<img src="img/logo-footer.png" alt="logo">';
echo '<figcaption>PC WORLDZ</figcaption>';
echo '</figure>';
echo '<!-- /LOGO -->';
echo '<p class="description">We are dedicated to give you the very best of Computer Products, with a focus on quality, price and uniqueness. Founded in 2022 by Saludo, Peralta and Aquino, PC WORLDZ serves customer worldwide, and are thrilled to be a part of the fair trade wing of the IT industry.</p>';
echo '';
echo '<!-- CONTACTUS LIST -->';
echo '<ul class="contactus-list">';
echo '<!-- CONTACTUS LIST ITEM -->';
echo '<li class="contactus-list-item">';
echo '<i class="s-icon icon-location-pin"></i>';
echo '<p>Marinduque, PH</p>';
echo '</li>';
echo '<!-- /CONTACTUS LIST ITEM -->';
echo '';
echo '<!-- CONTACTUS LIST ITEM -->';
echo '<li class="contactus-list-item">';
echo '<i class="s-icon icon-envelope"></i>';
echo '<a href="mailto:info@tricksterhelmets.com" class="link">info@pcworldz.com</a>';
echo '</li>';
echo '<!-- /CONTACTUS LIST ITEM -->';
echo '';
echo '<!-- CONTACTUS LIST ITEM -->';
echo '<li class="contactus-list-item">';
echo '<i class="s-icon icon-phone"></i>';
echo '<p>044 - 555 - 123 - 1234</p>';
echo '</li>';
echo '<!-- /CONTACTUS LIST ITEM -->';
echo '</ul>';
echo '<!-- /CONTACTUS LIST -->';
echo '</div>';
echo '<!-- /ABOUTUS PREVIEW -->';
echo '';
echo '<!-- CONTENT DROPDOWN COLUMN -->';
echo '<div class="content-dropdown-column">';
echo '<h6 class="title small secondary">Sitemap</h6>';
echo '<hr class="line-separator">';
echo '<!-- LINK LIST -->';
echo '<ul class="link-list decorated">';
echo '<!-- LINK LIST ITEM -->';
echo '<li class="link-list-item">';
echo '<a href="index.php">';
echo 'Home';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow tiny">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</a>';
echo '</li>';
echo '<!-- /LINK LIST ITEM -->';
echo '';
echo '<!-- LINK LIST ITEM -->';
echo '<li class="link-list-item">';
echo '<a href="aboutus.php">';
echo 'About Us';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow tiny">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</a>';
echo '</li>';
echo '<!-- /LINK LIST ITEM -->';
echo '';
echo '<!-- LINK LIST ITEM -->';
echo '<li class="link-list-item">';
echo '<a href="shop-grid.php">';
echo 'Shop';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow tiny">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</a>';
echo '</li>';
echo '<!-- /LINK LIST ITEM -->';
echo '';
echo '<!-- LINK LIST ITEM -->';
echo '<li class="link-list-item">';
echo '<a href="blog.php">';
echo 'Our Blog';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow tiny">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</a>';
echo '</li>';
echo '<!-- /LINK LIST ITEM -->';
echo '';
echo '<!-- LINK LIST ITEM -->';
echo '<li class="link-list-item">';
echo '<a href="contactus.php">';
echo 'Contact';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow tiny">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</a>';
echo '</li>';
echo '<!-- /LINK LIST ITEM -->';
echo '';
echo '<!-- LINK LIST ITEM -->';
echo '<li class="link-list-item">';
echo '<a href="profile.php">';
echo 'Your Account';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow tiny">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</a>';
echo '</li>';
echo '<!-- /LINK LIST ITEM -->';
echo '';
echo '<!-- LINK LIST ITEM -->';
echo '<li class="link-list-item">';
echo '<a href="#">';
echo 'FAQs';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow tiny">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</a>';
echo '</li>';
echo '<!-- /LINK LIST ITEM -->';
echo '';
echo '<!-- LINK LIST ITEM -->';
echo '<li class="link-list-item">';
echo '<a href="#">';
echo 'Our Guarantee';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow tiny">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</a>';
echo '</li>';
echo '<!-- /LINK LIST ITEM -->';
echo '</ul>';
echo '<!-- /LINK LIST -->';
echo '</div>';
echo '<!-- /CONTENT DROPDOWN COLUMN -->';
echo '';
echo '<!-- CONTENT DROPDOWN COLUMN -->';
echo '<div class="content-dropdown-column">';
echo '<h6 class="title small secondary">Company</h6>';
echo '<hr class="line-separator">';
echo '<!-- LINK LIST -->';
echo '<ul class="link-list decorated">';
echo '<!-- LINK LIST ITEM -->';
echo '<li class="link-list-item">';
echo '<a href="#">';
echo 'Shipping Policy';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow tiny">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</a>';
echo '</li>';
echo '<!-- /LINK LIST ITEM -->';
echo '';
echo '<!-- LINK LIST ITEM -->';
echo '<li class="link-list-item">';
echo '<a href="#">';
echo 'International Shipping';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow tiny">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</a>';
echo '</li>';
echo '<!-- /LINK LIST ITEM -->';
echo '';
echo '<!-- LINK LIST ITEM -->';
echo '<li class="link-list-item">';
echo '<a href="#">';
echo 'Affiliates';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow tiny">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</a>';
echo '</li>';
echo '<!-- /LINK LIST ITEM -->';
echo '';
echo '<!-- LINK LIST ITEM -->';
echo '<li class="link-list-item">';
echo '<a href="#">';
echo 'Our Sponsors';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow tiny">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</a>';
echo '</li>';
echo '<!-- /LINK LIST ITEM -->';
echo '';
echo '<!-- LINK LIST ITEM -->';
echo '<li class="link-list-item">';
echo '<a href="#">';
echo 'Privacy Policy';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow tiny">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</a>';
echo '</li>';
echo '<!-- /LINK LIST ITEM -->';
echo '';
echo '<!-- LINK LIST ITEM -->';
echo '<li class="link-list-item">';
echo '<a href="#">';
echo 'Terms and Conditions';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow tiny">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</a>';
echo '</li>';
echo '<!-- /LINK LIST ITEM -->';
echo '';
echo '<!-- LINK LIST ITEM -->';
echo '<li class="link-list-item">';
echo '<a href="#">';
echo 'Pay on Arrival';
echo '<!-- SVG ARROW -->';
echo '<svg class="svg-arrow tiny">';
echo '<use xlink:href="#svg-arrow"></use>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '</a>';
echo '</li>';
echo '<!-- /LINK LIST ITEM -->';
echo '</ul>';
echo '<!-- /LINK LIST -->';
echo '</div>';
echo '<!-- /CONTENT DROPDOWN COLUMN -->';
echo '';
echo '<!-- CONTENT DROPDOWN COLUMN -->';
echo '<div class="content-dropdown-column full">';
echo '<h6 class="title small secondary">Quick Contact</h6>';
echo '<hr class="line-separator">';
echo '<p class="description">You can contact by using our contact number or email us below by using our email info@pcworldz.com</p>';
echo '<form class="quick-contact-form">';
echo '<input type="text" class="dark" name="qc_email" placeholder="Email">';
echo '<textarea name="qc_message" class="dark" placeholder="Message"></textarea>';
echo '<button class="button small">Send Message</button>';
echo '</form>';
echo '</div>';
echo '<!-- /CONTENT DROPDOWN COLUMN -->';
echo '</div>';
echo '<!-- /FOOTER TOP -->';
echo '';
echo '<!-- FOOTER BOTTOM -->';
echo '<div class="footer-bottom">';
echo '<h6 class="title tiny secondary">Payment Methods:</h6>';
echo '<!-- PAYMENT LIST -->';
echo '<ul class="payment-list">';
echo '<!-- PAYMENT LIST ITEM -->';
echo '<li class="payment-list-item">';
echo '<a href="#">';
echo '<img src="img/home/card_01.png" alt="card01">';
echo '</a>';
echo '</li>';
echo '<!-- PAYMENT LIST ITEM -->';
echo '';
echo '<!-- PAYMENT LIST ITEM -->';
echo '<li class="payment-list-item">';
echo '<a href="#">';
echo '<img src="img/home/card_02.png" alt="card02">';
echo '</a>';
echo '</li>';
echo '<!-- PAYMENT LIST ITEM -->';
echo '';
echo '<!-- PAYMENT LIST ITEM -->';
echo '<li class="payment-list-item">';
echo '<a href="#">';
echo '<img src="img/home/card_03.png" alt="card03">';
echo '</a>';
echo '</li>';
echo '<!-- PAYMENT LIST ITEM -->';
echo '';
echo '<!-- PAYMENT LIST ITEM -->';
echo '<li class="payment-list-item">';
echo '<a href="#">';
echo '<img src="img/home/card_04.png" alt="card04">';
echo '</a>';
echo '</li>';
echo '<!-- PAYMENT LIST ITEM -->';
echo '';
echo '<!-- PAYMENT LIST ITEM -->';
echo '<li class="payment-list-item">';
echo '<a href="#">';
echo '<img src="img/home/card_05.png" alt="card05">';
echo '</a>';
echo '</li>';
echo '<!-- PAYMENT LIST ITEM -->';
echo '';
echo '<!-- PAYMENT LIST ITEM -->';
echo '<li class="payment-list-item">';
echo '<a href="#">';
echo '<img src="img/home/card_06.png" alt="card06">';
echo '</a>';
echo '</li>';
echo '<!-- PAYMENT LIST ITEM -->';
echo '</ul>';
echo '<!-- /PAYMENT LIST -->';
echo '</div>';
echo '<!-- /FOOTER BOTTOM -->';
echo '</footer>';
echo '<!-- /FOOTER WRAP -->';
echo '';
echo '<!-- WIDGET LINE WRAP -->';
echo '<div class="widget-line-wrap dark widget-line-copy">';
echo '<!-- WIDGET LINE -->';
echo '<div class="widget-line big">';
echo '<p class="copyright"><span class="bold">PC WORLDZ</span> | All Rights Reserved 2016</p>';
echo '<!-- ACTIONS LIST -->';
echo '<ul class="actions-list right">';
echo '<!-- ACTIONS LIST ITEM -->';
echo '<li class="actions-list-item">';
echo '<!-- SOCIAL LINK -->';
echo '<div class="social-link">';
echo '<a href="#">';
echo '<i class="fa fa-facebook"></i>';
echo '</a>';
echo '</div>';
echo '<!-- /SOCIAL LINK -->';
echo '</li>';
echo '<!-- ACTIONS LIST ITEM -->';
echo '';
echo '<!-- ACTIONS LIST ITEM -->';
echo '<li class="actions-list-item">';
echo '<!-- SOCIAL LINK -->';
echo '<div class="social-link">';
echo '<a href="#">';
echo '<i class="fa fa-twitter"></i>';
echo '</a>';
echo '</div>';
echo '<!-- /SOCIAL LINK -->';
echo '</li>';
echo '<!-- ACTIONS LIST ITEM -->';
echo '';
echo '<!-- ACTIONS LIST ITEM -->';
echo '<li class="actions-list-item">';
echo '<!-- SOCIAL LINK -->';
echo '<div class="social-link">';
echo '<a href="#">';
echo '<i class="fa fa-google-plus"></i>';
echo '</a>';
echo '</div>';
echo '<!-- /SOCIAL LINK -->';
echo '</li>';
echo '<!-- ACTIONS LIST ITEM -->';
echo '';
echo '<!-- ACTIONS LIST ITEM -->';
echo '<li class="actions-list-item">';
echo '<!-- SOCIAL LINK -->';
echo '<div class="social-link">';
echo '<a href="#">';
echo '<i class="fa fa-rss"></i>';
echo '</a>';
echo '</div>';
echo '<!-- /SOCIAL LINK -->';
echo '</li>';
echo '<!-- ACTIONS LIST ITEM -->';
echo '';
echo '<!-- ACTIONS LIST ITEM -->';
echo '<li class="actions-list-item">';
echo '<!-- SOCIAL LINK -->';
echo '<div class="social-link">';
echo '<a href="#">';
echo '<i class="fa fa-vimeo"></i>';
echo '</a>';
echo '</div>';
echo '<!-- /SOCIAL LINK -->';
echo '</li>';
echo '<!-- ACTIONS LIST ITEM -->';
echo '</ul>';
echo '<!-- ACTIONS LIST -->';
echo '</div>';
echo '<!-- WIDGET LINE -->';
echo '</div>';
echo '<!-- WIDGET LINE WRAP -->';
echo '';
echo '<!-- SVG ICONS -->';
echo '<!-- SVG ARROW -->';
echo '<svg style="display: none;">';
echo '<symbol id="svg-arrow" viewBox="0 0 3.923 6.64014" preserveAspectRatio="xMinYMin meet">';
echo '<path d="M3.711,2.92L0.994,0.202c-0.215-0.213-0.562-0.213-0.776,0c-0.215,0.215-0.215,0.562,0,0.777l2.329,2.329';
echo 'L0.217,5.638c-0.215,0.215-0.214,0.562,0,0.776c0.214,0.214,0.562,0.215,0.776,0l2.717-2.718C3.925,3.482,3.925,3.135,3.711,2.92z"/>';
echo '</symbol>';
echo '</svg>';
echo '<!-- /SVG ARROW -->';
echo '';
echo '<!-- SVG CHECK -->';
echo '<svg style="display: none;">';
echo '<symbol id="svg-check" viewBox="0 0 20 16" preserveAspectRatio="xMinYMin meet">';
echo '<path fill-rule="evenodd" clip-rule="evenodd" d="M19.692,3.398L7.764,15.669c-0.412,0.424-1.08,0.424-1.491,0';
echo 'L0.308,9.534C-0.104,9.11-0.104,8.423,0.308,8l1.491-1.534c0.412-0.424,1.08-0.424,1.491,0l3.728,3.834L16.71,0.33';
echo 'c0.412-0.423,1.08-0.423,1.491,0l1.491,1.534C20.104,2.288,20.104,2.975,19.692,3.398z"/>';
echo '</symbol>';
echo '</svg>';
echo '<!-- /SVG CHECK -->';
echo '';
echo '<!-- SVG MAG GLASS -->';
echo '<svg style="display: none;">';
echo '<symbol id="svg-mag-glass" viewBox="0 0 12 12" preserveAspectRatio="xMinYMin meet">';
echo '<path d="M3.094,6.916c-0.275-0.269-0.482-0.573-0.62-0.912C2.336,5.666,2.267,5.32,2.267,4.968';
echo 'c0-0.351,0.069-0.699,0.207-1.041c0.138-0.344,0.345-0.65,0.62-0.92c0.275-0.269,0.587-0.468,0.934-0.599';
echo 'c0.347-0.13,0.702-0.195,1.066-0.195s0.72,0.064,1.067,0.195c0.346,0.131,0.657,0.331,0.933,0.599c0.275,0.27,0.482,0.576,0.62,0.92';
echo 'c0.139,0.342,0.207,0.69,0.207,1.041c0,0.353-0.068,0.698-0.207,1.036c-0.138,0.339-0.345,0.644-0.62,0.912';
echo 'c-0.275,0.27-0.587,0.471-0.933,0.605C5.813,7.657,5.458,7.724,5.094,7.724s-0.72-0.066-1.066-0.202';
echo 'C3.681,7.387,3.369,7.186,3.094,6.916z M1.494,1.443C0.996,1.93,0.622,2.479,0.374,3.092C0.125,3.705,0,4.328,0,4.962';
echo 's0.125,1.257,0.374,1.87c0.248,0.611,0.622,1.161,1.12,1.648c0.399,0.391,0.844,0.703,1.333,0.938';
echo 'c0.488,0.234,0.995,0.391,1.52,0.469c0.525,0.078,1.052,0.074,1.58-0.013C6.456,9.786,6.961,9.621,7.44,9.379l2.294,2.241';
echo 'c0.133,0.13,0.28,0.226,0.44,0.286c0.159,0.061,0.326,0.091,0.5,0.091c0.173,0,0.34-0.03,0.5-0.091s0.307-0.156,0.439-0.286';
echo 'c0.134-0.13,0.231-0.274,0.293-0.431c0.063-0.156,0.094-0.318,0.094-0.488s-0.031-0.332-0.094-0.488';
echo 'c-0.062-0.157-0.159-0.301-0.293-0.431L9.401,7.619C9.712,7.143,9.93,6.63,10.055,6.082c0.124-0.547,0.157-1.094,0.1-1.641';
echo 'c-0.058-0.547-0.209-1.08-0.453-1.596c-0.245-0.517-0.58-0.983-1.007-1.401C8.196,0.967,7.634,0.605,7.008,0.363';
echo 'C6.381,0.119,5.743-0.003,5.094-0.003S3.808,0.119,3.181,0.363C2.554,0.605,1.991,0.967,1.494,1.443z"/>';
echo '</symbol>';
echo '</svg>';
echo '<!-- /SVG MAG GLASS -->';
echo '';
echo '<!-- SVG CROSS -->';
echo '<svg style="display: none;">';
echo '<symbol id="svg-cross" viewBox="0 0 10 10" preserveAspectRatio="xMinYMin meet">';
echo '<g>';
echo '<g>';
echo '<polygon fill-rule="evenodd" clip-rule="evenodd" points="9.949,1.465 8.535,0.051 5,3.586 1.465,0.051';
echo '0.051,1.465 3.586,5 0.051,8.535 1.465,9.949 5,6.414 8.535,9.949 9.949,8.535 6.414,5 		"/>';
echo '</g>';
echo '</g>';
echo '</symbol>';
echo '</svg>';
echo '<!-- /SVG CROSS -->';
echo '';
echo '<!-- SVG CART -->';
echo '<svg style="display: none;">';
echo '<symbol id="svg-cart" viewBox="0 0 22 18" preserveAspectRatio="xMinYMin meet">';
echo '<g>';
echo '<g>';
echo '<path fill-rule="evenodd" clip-rule="evenodd" d="M16.991,13.991c-1.106,0-2.003,0.896-2.003,2.003s0.896,2.003,2.003,2.003';
echo 's2.003-0.896,2.003-2.003S18.098,13.991,16.991,13.991z M8.012,13.991c-1.105,0-2.003,0.896-2.003,2.003s0.897,2.003,2.003,2.003';
echo 'c1.106,0,2.003-0.896,2.003-2.003S9.118,13.991,8.012,13.991z M5,2V1c0-0.552-0.447-1-1-1H1C0.447,0,0,0.448,0,1v1';
echo 'c0,0.553,0.447,1,1,1h2.182L5,13h15l2-11H5z M18.331,11H6.669L5.396,4h14.207L18.331,11z"/>';
echo '</g>';
echo '</g>';
echo '<rect x="3.734" fill-rule="evenodd" clip-rule="evenodd" width="1.266" height="3"/>';
echo '</symbol>';
echo '</svg>';
echo '<!-- /SVG CART -->';
echo '';
echo '<!-- SVG STAR -->';
echo '<svg style="display: none;">';
echo '<symbol id="svg-star" viewBox="0 0 15 14" preserveAspectRatio="xMinYMin meet">';
echo '<path fill-rule="evenodd" clip-rule="evenodd" d="M7.5-0.002l2.473,4.399L15,5.345l-3.5,3.667l0.636,4.985';
echo 'L7.5,11.863l-4.635,2.134L3.5,9.012L0,5.345l5.028-0.948L7.5-0.002"/>';
echo '</symbol>';
echo '</svg>';
echo '<!-- /SVG STAR -->';
echo '';
echo '<!-- SVG CART SMALL -->';
echo '<svg style="display: none;">';
echo '<symbol id="svg-cart-small" viewBox="0 0 16 13" preserveAspectRatio="xMinYMin meet">';
echo '<g>';
echo '<g>';
echo '<path fill-rule="evenodd" clip-rule="evenodd" d="M12.49,10.012c-0.826,0-1.495,0.669-1.495,1.493';
echo 'c0,0.825,0.669,1.494,1.495,1.494s1.495-0.669,1.495-1.494C13.985,10.681,13.316,10.012,12.49,10.012z M5.497,10.012';
echo 'c-0.826,0-1.495,0.669-1.495,1.493c0,0.825,0.669,1.494,1.495,1.494c0.825,0,1.495-0.669,1.495-1.494';
echo 'C6.992,10.681,6.322,10.012,5.497,10.012z M4,1.001v-1H1c-0.553,0-1,0.448-1,1s0.447,1,1,1h1.25l1.75,7h10l2-8H4z M12.438,7.001';
echo 'H5.561l-1-4h8.877L12.438,7.001z"/>';
echo '</g>';
echo '</g>';
echo '</symbol>';
echo '</svg>';
echo '<!-- /SVG CART SMALL -->';
echo '';
echo '<!-- SVG HEART -->';
echo '<svg style="display: none;">';
echo '<symbol id="svg-heart" viewBox="0 0 14 12" preserveAspectRatio="xMinYMin meet">';
echo '<path d="M10.043,1.998c0.55,0,0.95,0.167,1.381,0.577c0.371,0.353,0.575,0.813,0.575,1.297';
echo 'c0,0.484-0.204,0.945-0.591,1.313C11.384,5.208,11.34,5.25,7.002,9.705C5.717,8.346,2.975,5.451,2.576,5.071';
echo 'C2.205,4.719,2,4.258,2,3.774s0.204-0.943,0.576-1.296C2.823,2.243,3.178,2.003,3.93,2.003c0.209,0,0.802,0.225,1.702,1.069';
echo 'l1.39,1.303l1.369-1.325C9.213,2.255,9.858,1.998,10.043,1.998 M10.043-0.002C9.011-0.002,7.859,0.782,7,1.613';
echo 'c-0.887-0.832-2.003-1.61-3.07-1.61c-1.045,0-1.965,0.297-2.731,1.025c-1.598,1.517-1.598,3.976,0,5.493';
echo 'c0.456,0.434,4.883,5.121,4.883,5.121c0.252,0.24,0.583,0.359,0.914,0.359c0.33,0,0.66-0.119,0.912-0.359';
echo 'c0,0,4.843-4.974,4.895-5.024c1.597-1.517,1.597-3.977,0-5.494C12.009,0.372,11.123-0.002,10.043-0.002L10.043-0.002z"/>';
echo '</symbol>';
echo '</svg>';
echo '<!-- /SVG HEART -->';
echo '';
echo '<!-- SVG BURGER -->';
echo '<svg style="display: none;">';
echo '<symbol id="svg-burger" viewBox="0 0 22 14" preserveAspectRatio="xMinYMin meet">';
echo '<g>';
echo '<g>';
echo '<path fill-rule="evenodd" clip-rule="evenodd" d="M1,2h20c0.553,0,1-0.448,1-1s-0.447-1-1-1H1C0.448,0,0,0.448,0,1';
echo 'S0.448,2,1,2z M21,6H1C0.448,6,0,6.448,0,7c0,0.553,0.448,1,1,1h20c0.553,0,1-0.447,1-1C22,6.448,21.553,6,21,6z M21,12H1';
echo 'c-0.552,0-1,0.447-1,1s0.448,1,1,1h20c0.553,0,1-0.447,1-1S21.553,12,21,12z"/>';
echo '</g>';
echo '</g>';
echo '</symbol>';
echo '</svg>';
?>
  <!-- /SVG BURGER -->
<!-- /SVG ICONS -->

<!-- jQuery -->
<script src="js/vendor/jquery-3.1.0.min.js"></script>
<!-- magnificPopup -->
<script src="js/vendor/jquery.magnific-popup.min.js"></script>
<!-- imgLiquid -->
<script src="js/vendor/imgLiquid-min.js"></script>
<!-- liquid -->
<script src="js/liquid.js"></script>
<!-- dropdowns -->
<script src="js/dropdowns.js"></script>
<!-- popups -->
<script src="js/popups.js"></script>
<!-- tab -->
<script src="js/tab.js"></script>
<!-- rating -->
<script src="js/rating.js"></script>
<!-- image changer -->
<script src="js/image_changer.js"></script>
<!-- counter -->
<script src="js/counter.js"></script>
<!-- zoomifier -->
<script src="js/zoomifier.js"></script>
</body>
</html>
